services:
  - type: background_worker  # ← This is the new correct type
    name: real-estate-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        type: secret
      - key: RAZORPAY_KEY
        type: secret
      - key: RAZORPAY_SECRET
        type: secret
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString
    plan: free

databases:
  - name: real-estate-db
    plan: free
