services:
  - type: web
    name: Realestate
    runtime: python
    buildCommand: |
      poetry install --no-interaction --no-ansi --no-root
      python -m App.database
    startCommand: |
      poetry run gunicorn App.main:app \
      --workers 1 \
      --threads 4 \
      --bind 0.0.0.0:10000 \
      --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        type: secret
      - key: DATABASE_URL
        fromDatabase:
          name: Realestate-db
          property: connectionString
    plan: free

databases:
  - name: Realestate-db
    databaseName: Realestate_db
    user: Realestate_user
    plan: free
