services:
  - type: web
    name: real-estate-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m app.database
    startCommand: |
      gunicorn app.main:app \
      --workers 1 \
      --threads 4 \
      --worker-class uvicorn.workers.UvicornWorker \
      --bind 0.0.0.0:10000 \
      --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        type: secret
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString
    plan: free
    healthCheckPath: /health
